version: '3'

services:
  motionms:
    build: .
    environment:
      - MQTT_HOST=mosquitto
      - SPRING_CLOUD_VAULT_URI=http://vault:8200
      - SPRING_CLOUD_VAULT_TOKEN=${VAULT_TOKEN}
    ports:
      - 3000:3000
    volumes:
      - ${MOTION_HOME_PATH}:/home/motion:ro
    depends_on:
      - mosquitto
      - vault

  vault:
    image: vault:latest
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
      - VAULT_HOME=${VAULT_HOME}
    volumes:
      - ./tools/vault/config:/vault/config
      - ${VAULT_HOME}:/vault/data
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.hcl

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ./tools/mosquitto/config:/mosquitto/config
